# runs the machine-status script
sudo ./machine-status.sh

#text to pdf:
f1="machine-status-report.txt"
f2="log-status-report.txt"

a1=machine-status-report.pdf
a2=log-status-report.pdf

sudo enscript -p out.ps ${f1}
ps2pdf out.ps ${a1}
sudo rm out.ps ${f1}

sudo enscript -p out.ps ${f2}
ps2pdf out.ps ${a2}
sudo rm out.ps ${f2}

# send out the file --------------------------------
smtp="smtp.googlemail.com:587"

## use an email that you dont care about
from="XXXX@gmail.com"
to="XXXX@XXX.XX"

username="XXXX"
password="XXXX!"

## do not include hyphens in text body

subject="$(date +%F): Weekly machine status report."
message="Dear Cluster Managers. This week's reports are attached."

## attachments
#a1="machine-status-report.pdf"
#a2="machine-status-report.txt"

sendEmail -f ${from} -t ${to} \
-u ${subject} \
-m ${message} \
-s ${smtp} \
-xu ${username} -xp ${password} \
-a ${a1} \
-a ${a2} | grep successful

if [ $? -eq 1 ]
then
        sendEmail -f ${from} -t ${to} \
        -u "IMPORTANT: Weekly machine-status report failed!" \
        -m "Dear Cluster Managers, the weekly status report generated by bw-admin @ thing6 failed to send the email with report attachments successfully. Thank you." \
        -s ${smtp} -xu ${username} -xp ${password}
fi

sudo rm ${a1} ${a2}
